### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [Ashishjshetty/is-connected#1]
I copied the example code in and ran it a bit.  If I leave it alone and let it run, it provides "Internet connected" messages as expected.

Next I entered my adapter settings and disabled my ethernet (thus disconnecting my internet).  This caused the program to simply stop outputting.  It didn't freeze or crash, simply stopped console logging statuses.  This continued for about 2 minutes, at which point it began logging "not connected" messages.  I then re-enabled my adapter.  However, the program continued to log "not connected" messages long after my internet connectivity had re-established, at least 7 minutes after the internet came back up.  This is all using the DNS mode.

Using Ping mode, the program simply logs "not connected" no matter what.  

npm version 3.8.9
node version 6.2.0

Edit: Using dns.lookup instead of dns.resolve fixes the dns issues.

**Comment by Ashishjshetty** [comment]
I am not quite sure how it didnt work for you. I tested it the following way and it worked for me.
1. start app. with internet connected , got correct event of connected.
2. used  `sudo ifconfig wlan0 down` to disable interface, got disconnected event.
3. used `sudo ifconfig wlan0 up` after a while to enable interface. got connected event after wifi re-connection.

Now i did the same thing with Ethernet and i got the same results. May be you could list down steps you took, so that i can maybe recreate what you experienced?, and the reason for not including lookup was [this](https://github.com/Ashishjshetty/is-connected/pull/2#issuecomment-246128806)

**Comment by ghost** [comment]
Alright.  My system is as described up above, npm 3.8.9, node 6.2.0.  I also sped up the checkInterval to 1000, to make testing easier.
1. Copied your example code from the readme into a .js file, with is-connected downloaded as a node module.
2. Ran the program with internet connected, everything seems to work fine.
3. Disabled my adapter.  Got one "internet not connected" message, then messages stopped.  
4. After 1.5 minutes, "internet not connected" messages resumed printing, though slower than usual and definitely not once a second.  It gradually sped up, though they seemed to print irregularly.
5. I then enabled my adapter and reloaded a page to confirm I indeed have internet again.  However, the "internet disconnected" messages continued to print forever.

I tried it again at the normal 10000 and it did the same thing.

So it seems that the possible differences could be 
1. Our node versions
2. Windows vs Linux
3. Some oddness with my network, I suppose.  My normal internet connectivity doesn't seem to have any issues, so I'm not sure what would be the issue there.

I can get a linux PC set up later to see if it behaves any differently on that platform.

**Comment by Ashishjshetty** [comment]
Operating system may cause a difference, I useed it on Linux, I also have
been using it with my application and haven't faced any issues. Windows may
have a difference in behaviour. Can you check on Linux? Maybe a Vm may help
I will check on Windows as soon as possible.

**Comment by Ashishjshetty** [comment]
i can confirm now that the issue is successfully recreated with windows operating systems. i am thinking of  adding lookup as well, which may solve your problem. will look into further what may be causing the problem in windows.

**Comment by Ashishjshetty** [comment]
@DarkArcher117 I have made some changes to accommodate windows difference in behavior, should solve your problem. Will investigate a bit furthur into why do windows have such behavior when you try to dns resolve a host as compared to dns lookup. Thanks for you input
